#Includes:
#Database credentials
#AWS Glue job parameters such as region, timeout, batch size, logging
#S3 zones for raw and curated data
#sns topic for ARN notification
#Common section as applies

#Configuartion
DEV:
#database
    aws_db_user: some user
    aws_db_name: orders
    aws_db_port: 5432 (PG)
    aws_db_host: some_host
    aws_cert_loc: s3://bucketname/common/postgres/global_bundle.pem

aws_catalog: AWSDataCatalog
sns_topic: arn:aws:daily_orders-sns
batch_size:0 #0:ALL
log_level: DEBUG

#source_zone: s3://bucketname
#curated_zone: s3://bucketname

COMMON:

aws_region: us-east-1
log_dir: log
log_level: INFO
process_name: order_daily
database_name: orders
table_write_mode:append









